# -------------1------------------
print(ord("A"))
print(chr(65))
print(chr(98))
print("char: \u0489")
print("char: \u2DBB")
print("char: \052")
print("char: \x2a")
print("char: \u000Areza")
print("char: \x0areza")
print("char: \nreza")
print("char: reza\b")
print("char: reza\u0008")
print("char: \rreza")
print("char: re\tza")